# Generated by Django 5.1.7 on 2025-05-08 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='last_edited',
        ),
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.AddField(
            model_name='document',
            name='editors',
            field=models.ManyToManyField(related_name='editable_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
